import canonicalLaneMathlib.AdmissibleClass
import DynamicRenormalizationGroupMethodsAppliedLemmaCanonicalLaneLean.BridgeLemmas
import DynamicRenormalizationGroupMethodsAppliedLemmaCanonicalLaneLean.GateLemmas
import DynamicRenormalizationGroupMethodsAppliedLemmaCanonicalLaneLean.FinalTheorem
import DynamicRenormalizationGroupMethodsAppliedLemmaCanonicalLaneLean.DynamicRenormalizationGroupKernel
import DynamicRenormalizationGroupMethodsAppliedLemmaCanonicalLaneLean.FixedPointClassification
import DynamicRenormalizationGroupMethodsAppliedLemmaCanonicalLaneLean.BetaFunctionFlow
import DynamicRenormalizationGroupMethodsAppliedLemmaCanonicalLaneLean.CriticalExponentCalculation
import DynamicRenormalizationGroupMethodsAppliedLemmaCanonicalLaneLean.WilsonFisherFixedPoint

namespace HautevilleHouse
namespace DynamicRenormalizationGroupMethodsAppliedLemmaCanonicalLaneLean

-- Package-level check that all closures are consistent
theorem all_closures_consistent (A : AdmissibleClass) :
    ConstrainedDynamicRenormalizationClosure A :=
  constrained_dynamic_renormalization_endgame A

end DynamicRenormalizationGroupMethodsAppliedLemmaCanonicalLaneLean
end HautevilleHouse